### ISSUE TITLE
Define the resurfacing location

### ISSUE THREAD

**Issue by Comquister** [VictorTedesco/BetterDeathScreen#4]
put a function to set the location when you die like
0, 84, 0, 90, 0: Spawn 

if registered in bed

**Comment by VictorTedesco** [comment]
I didn't understand, looks like you want me to create a spawn system, the plugins uses the default spawn of the main world, you can set it with /setworldspawn. But in the 1.4.1 update, i will create a spawn system.

**Comment by Comquister** [comment]
Mas o /setworldspawn só funciona no mundo principal
But /setworldspawn only works on the main world

Desculpe pelo inglês, mas estou a usar o Google Translator e falo português
Sorry for the English, but I am using Google Translator and I speak Portuguese

**Comment by VictorTedesco** [comment]
Então pelo o que parece seu mundo de spawn não é o mundo principal, não pensei nesse tipo de organização de mundos, vou trabalhar no sistema  de setar spawn. Sou brasileiro, não se preocupe.

**Comment by Comquister** [comment]
tem alguma previsão da atualização?
ou vai esperar lançar a 1.19

**Comment by VictorTedesco** [comment]
Clona e builda esse ultimo commit que eu fiz, ja implementei o sistema que você pediu, mas não testei muitas vezes.

**Comment by Comquister** [comment]
Sé eu soubesse como faz eu faria, Eu espero sair no [Releases](https://github.com/VictorTedesco/BetterDeathScreen/releases)

**Comment by Comquister** [comment]
Deu um erro quando tentei fazer uma build da 1.5
```java
[22:08:24 INFO]: [BetterDeathScreen] Enabling BetterDeathScreen v1.5
[22:08:24 WARN]: [BetterDeathScreen] Loaded class org.bstats.bukkit.Metrics from antiRedstoneClock v1.5.0 which is not a depend or softdepend of this plugin.
[22:08:24 ERROR]: Error occurred while enabling BetterDeathScreen v1.5 (Is it up to date?)
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
     at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:220) ~[antiRedstoneClock-1.5.0.jar:?]
     at org.bstats.MetricsBase.<init>(MetricsBase.java:104) ~[antiRedstoneClock-1.5.0.jar:?]
     at org.bstats.bukkit.Metrics.<init>(Metrics.java:74) ~[antiRedstoneClock-1.5.0.jar:?]
     at me.tedesk.BetterDeathScreen.onEnable(BetterDeathScreen.java:93) ~[BetterDeathScreen-1.5.jar:?]
     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1628]
     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1628]
     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1628]
     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1628]
     at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1628]
     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1628]
     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1628]
     at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:08:24 INFO]: [BetterDeathScreen] Disabling BetterDeathScreen v1.5
[22:08:24 INFO]: [BetterDeathScreen] Plugin desativado! (v1.5)
```

**Comment by VictorTedesco** [comment]
Lancei uma nova release com o seu pedido.
